### ISSUE TITLE
Не работает с png

### ISSUE THREAD

**Issue by bronewi4ok** [xvoland/gulp-xv-webp-html#1]
Для изображений с расширением .png тег picture добавляется, но .png не меняется на .webp. Хотя для .jpg  все работает отлично.

**Comment by xvoland** [comment]
Всё работает.
Вы, не включили обработку .png файлов, по умолчанию обрабатываются jpg, svg.

было:
`.pipe(webp_html(['.jpg', '.svg']))`

стало:
`.pipe(webp_html(['.jpg', '.svg', '.png']))`

**Comment by bronewi4ok** [comment]
Я все включил. 
.pipe(webphtml(['.jpg', '.png', '.svg']))
Однако на выходе вот такой результат:
`                <picture>
                    <source srcset="img/cmn/logo.png">
                    <img class="logo__img" src="img/cmn/logo.png" alt="logo">
                </picture>
`
webp не появляется.
А потом я случайно опечатался и пропустил точку перед png, т.е. вот так записал:
        .pipe(webphtml(['.jpg', 'png', '.svg']))
И получил немного другой результат:
`
                <picture>
                    <source srcset="img/cmn/logo..webp" type="image/webp">
                    <source srcset="img/cmn/logo.png" type="image/jpeg">
                    <img class="logo__img" src="img/cmn/logo.png" alt="logo">
                </picture>
`
webp появился, но с лишней точкой перед расширением файла: logo..webp
При этом с jpg таких проблем нет, все работает корректно.

**Comment by xvoland** [comment]
Спасибо.
Не помню почему я так сделал, возможно, где-то какой-то стандарт.
Обновил до v1.1.2
